version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      # Auth AWS
      - echo Authenticating into AWS ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 040133161491.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building Backend Image
      - docker build -t webrevived-backend:latest -f apps/backend/Dockerfile .

      - echo Building Frontend Image
      - docker build -t webrevived-frontend:latest -f apps/frontend/Dockerfile .

      # Tag docker images
      - echo Tagging [Backend, Frontend] image...
      - docker tag webrevived-backend:latest 040133161491.dkr.ecr.us-east-1.amazonaws.com/webrevived-backend:latest
      - docker tag webrevived-frontend:latest 040133161491.dkr.ecr.us-east-1.amazonaws.com/webrevived-frontend:latest

  post_build:
    commands:
      - echo Pushing Backend image...
      - docker push 040133161491.dkr.ecr.us-east-1.amazonaws.com/webrevived-backend:latest

      - echo Pushing Frontend image...
      - docker push 040133161491.dkr.ecr.us-east-1.amazonaws.com/webrevived-frontend:latest

artifacts:
  files:
    - imagedefinitions.json
