version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - echo Installing dependices
      - npm install

  build:
    commands:
      - echo Running build command
