version: 0.1

env:
    variables:
        CACHE_CONTROL: "86400"
        BUILD_FOLDER: "build"

phases:
  install:
    commands:
      - echo installing nodejs...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs  #aws code build use ubuntu environement
  pre_build:
    commands:
      - echo installing dependencies...
      - npm install -w website
  build:
    commands:
      - echo building...
      - npm run build -w website

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: apps/website/build
