version: 0.1

env:
    variables:
        CACHE_CONTROL: "86400"
        BUILD_FOLDER: "build"

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo installing dependencies...
      - npm install -w website
  build:
    commands:
      - echo building...
      - npm run build -w website

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: apps/website/build
