version: '3'

services:
  nginx:
    container_name: webrevived-nginx
    build:
      context: ./apps/nginx
    depends_on:
      - frontend
      - backend
    volumes:
      - /nginx/nginx.conf:/etc/nginx.conf
    ports:
      - 80:80

  frontend:
    container_name: webrevived-frontend
    hostname: frontend
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - 3000:3000
    restart: on-failure

  backend:
    container_name: webrevived-backend
    hostname: backend
    env_file: apps/backend/.env
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - 5000:5000
    restart: always
